# Generated by Django 4.1.7 on 2023-03-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_s', models.IntegerField()),
            ],
        ),
    ]
