# Generated by Django 4.1.7 on 2023-03-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_s', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autosys',
            old_name='a_s',
            new_name='autosys',
        ),
    ]
