# Generated by Django 4.1.7 on 2023-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_s', '0002_rename_a_s_autosys_autosys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosys',
            name='autosys',
            field=models.IntegerField(unique=True),
        ),
    ]
